version: '3.8'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  app:
    build: .
    restart: always
    container_name: back
    ports:
      - '5000:3000'
    environment:
      APP_NAME: pi
      PORT: 3000
      DB_URI: mongodb://db:27017/pi
    depends_on:
      - db
    volumes:
      - mongo-data:/path/in/container
volumes:
  mongo-data:
