version: '3.8'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always

  app:
    build: .
    restart: always
    container_name: back
    ports:
      - '5000:3000'
    depends_on:
      - db
    volumes:
      - mongo-data:/path/in/container
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge
